/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controle.Controlador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.Responsavel;

/**
 *
 * @author Vinicius
 */
public class TelaBuscaResponsavel extends javax.swing.JDialog {
    private boolean selecionado = false;
    //Cria modelo de tabela, será usado na manipulação da mesma
    DefaultTableModel tabela;
    private int idResponsavel;
    
    /**
     * Creates new form TelaBuscaResponsavel
     */
    public TelaBuscaResponsavel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        consultarResponsaveis();
    }

    public int getIdResponsavel() {
        return idResponsavel;
    }

    public boolean isSelecionado() {
        return selecionado;
    }
    
    /**
     * Ao selecionar um responsavel, atualiza idSelecionado, o verificador e
     * fecha a janela
     */
    private void selecionaResponsavel(){
        selecionado = true;
        this.dispose();
    }
    private void consultarResponsaveis(){
        ArrayList<Responsavel> listaDeResponsaveis = Controlador.getListaDeResponsaveis();
        if (listaDeResponsaveis.size() > 0) {
            //Recria a tabela caso ela tenha sido modificada            
            tabelaResponsavel.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {
                     "Nome", "Código", "Telefone", "E-Mail", "idResponsavel"
                })
                {
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false
                };

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }}
            );
            //define a tabela com o mesmo modelo da tabelaResponsavel
            tabela = (DefaultTableModel) tabelaResponsavel.getModel();

            //Cria um objeto dadosDaLinhaNaColuna, onde cada posição é será coluna
            Object dadosDaLinhaNaColuna[] = new Object[5];
            //percorre o lista e popula as colunas de acordo com a posicao
            for (int i = 0; i < listaDeResponsaveis.size(); i++) {               
                
                //Busca na lista de equipamentos o idEquipamento do emprestimo atual
                dadosDaLinhaNaColuna[0] = listaDeResponsaveis.get(i).getNome();
                dadosDaLinhaNaColuna[1] = listaDeResponsaveis.get(i).getCodigo();
                dadosDaLinhaNaColuna[2] = listaDeResponsaveis.get(i).getTelefone();
                dadosDaLinhaNaColuna[3] = listaDeResponsaveis.get(i).getEmail();
                dadosDaLinhaNaColuna[4] = listaDeResponsaveis.get(i).getIdResponsavel();
                
                //Adiciona os dados à linha na tabela
                tabela.addRow(dadosDaLinhaNaColuna);                

            }
            //Define o autoresize pra 3, não lembro qual o motivo.
            tabelaResponsavel.setAutoResizeMode(3);
            //Oculta última coluna que é apenas para passar referência
            tabelaResponsavel.getColumnModel().getColumn(4).setMinWidth(0);
            tabelaResponsavel.getColumnModel().getColumn(4).setMaxWidth(0);
            jScrollPane1.getVerticalScrollBar().setValue(0);
        } else { //Se estiver vazia, avisa o usuário
            //exibirMensagem();
            JOptionPane.showMessageDialog(this, "Nenhum responsável cadastrado.");
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblBuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaResponsavel = new javax.swing.JTable();
        btnSeleciona = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setText("Tela busca responsavel");

        txtBuscar.setText("1");

        btnBuscar.setText("Buscar");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblBuscar.setText("Digite o nome do responsável");

        tabelaResponsavel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Código", "Telefone", "E-Mail", "idResponsavel"
            }
        ));
        tabelaResponsavel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaResponsavelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaResponsavel);
        if (tabelaResponsavel.getColumnModel().getColumnCount() > 0) {
            tabelaResponsavel.getColumnModel().getColumn(4).setMinWidth(0);
            tabelaResponsavel.getColumnModel().getColumn(4).setPreferredWidth(0);
            tabelaResponsavel.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        btnSeleciona.setText("Seleciona");
        btnSeleciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSeleciona)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBuscar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnSeleciona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSelecionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionaActionPerformed
        selecionaResponsavel();
    }//GEN-LAST:event_btnSelecionaActionPerformed

    private void tabelaResponsavelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaResponsavelMouseClicked
        //Armazena o id presente na coluna 4 da linha clicada em idResponsavel
        idResponsavel = (int) tabelaResponsavel.getValueAt(tabelaResponsavel.getSelectedRow(), 4);
        if (evt.getClickCount() == 2) {
            System.out.println("2 cliques no ID:" + idResponsavel);
            selecionaResponsavel();
        } else {
            //selecionaTermo(idTermoSelecionado);
            System.out.println("1 clique no ID " + idResponsavel);
        }
    }//GEN-LAST:event_tabelaResponsavelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaBuscaResponsavel dialog = new TelaBuscaResponsavel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeleciona;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tabelaResponsavel;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
